### ISSUE TITLE
License incompatible with UE4

### ISSUE THREAD

**Issue by shayneoAtNorwood** [tsky1971/UEZeroMQPlugin#1]
Hey guys, I appreciate what your doing here, its a pretty exciting idea, however you might have a problem with your license choice.

UE4 unfortunately is incompatible with GPL code, as while its quasi open source, its not free software in the FSF definition of the word and has restrictions that violate the GPL. 

What you COULD do however is use an LGPL license, as long as the build settings are set up correctly to ensure its not statically linked, as the LGPL does allow dynamically linked combinations with non free software, as long as any changes to your code are distributed back onto github or whatever.

Finally , you need to also check UE4s license as it likely contains phraseology prohibiting combining with non compatible licenses.

To be clear: I am not a lawyer, so you should NOT take this as advice, however I could shoot a letter off to the FSF to get someone to check in and give a more canonical answer, if you wish.

**Comment by tsky1971** [comment]
Hi shayneoAtNorwood,
thank you for this advise i will change this.
T.

**Comment by shayneoAtNorwood** [comment]
Good stuff mate. Your best bet is to just use an MIT or Mozilla license or something like that.
